# Time in seconds between each ping is sent
interval: 5
# Time in seconds before a ping with no response is considered lost
timeout: 3
# Number of packets to consider for calculation of metrics (min, max, avg, jit, loss)
history: 100
# Port to run the web server on for prometheus metrics. This must match the port in the prometheus config
port: 3009
# List of hosts to ping
endpoints:
  - 1.1.1.1 # Cloudflare
  - 8.8.8.8 # Google DNS
  - 8.8.4.4 # Google DNS
  - 156.240.3.35 # Facebook
  - 208.67.222.222 # Cisco OpenDNS
  - 208.67.220.220 # Cisco OpenDNS
  - 85.117.240.9 # TF2 Server US
  - 193.221.192.31 # TF2 Server UK
