# Time in milliseconds between each ping
interval: 3000
# Time in milliseconds before a ping with no response is considered lost
timeout: 3500
# Port to run the web server on for Prometheus metrics. This must match the port in the Prometheus config
port: 3009
# Name of host running the service for Prometheus metrics
localhost: 127.0.0.1
# List of hosts to ping
endpoints:
  - 
    hostname: cloudflare_dns
    address: 1.1.1.1
    location: los_angeles_ca
  - 
    hostname: google_dns
    address: 8.8.8.8
    location: mountain_view_ca
