# Time in milliseconds between each ping
interval: 3000
# Time in milliseconds before a ping with no response is considered lost
timeout: 3500
# Port to run the web server on for prometheus metrics. This must match the port in the prometheus config
port: 3009
# Name of host running service for prometheus metrics
localhost: home
# List of hosts to ping
endpoints:
  - 
    hostname: cloudflare_dns
    address: 1.1.1.1
    location: los_angeles_ca
  - 
    hostname: google_dns
    address: 8.8.8.8
    location: mountain_view_ca
  - 
    hostname: open_dns
    address: 208.67.222.222
    location: san_francisco_ca