# Time in seconds between each ping is sent
interval: 1
# Time in seconds before a ping with no response is considered lost
timeout: 3
# Number of packets to consider for calculation of metrics (min, max, avg, jit, loss)
history: 100
# List of hosts to ping
endpoints:
  #- 1.1.1.1 # Cloudflare
  - 8.8.8.8 # Google DNS
  - 8.8.4.4 # Google DNS
  #- 156.240.3.35 # Facebook
  #- 208.67.222.222 # Cisco OpenDNS
  #- 208.67.220.220 # Cisco OpenDNS